image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: pipenv install
  - command: pipenv run pytest tests/

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.6.8:4e210c3a3deb81ca178839c6ce3d5e6a
    - hbenl.vscode-test-explorer@2.19.6:66ef20d8117798aa03820a0c8cb7cc47